# Learn basic numpy

## Arrays

In [7]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)   # shape: tuple of array dimensions
print(a[2])
a[0]=5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[1,1])

<class 'numpy.ndarray'>
(3,)
3
[5 2 3]
(2, 3)
5


### example - object destructure


In [9]:
info=['tom', 'male', 38, 'winkriver\'s town']
name, sex, *other = info
print(name, sex)
print(other)

tom male
[38, "winkriver's town"]


### create arrays

In [10]:
import numpy as np

a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b)

c = np.full((2,3),7)   # create a constant array
print(c)

d = np.eye(2)   # create a 2x2 identity matrix
print(d)

e = np.random.random((2,3))
print(e)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7 7]
 [7 7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.15396928  0.07343066  0.64046725]
 [ 0.62651156  0.00098579  0.81257487]]


### Array indexing

#### Slicing

In [15]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice is a view into the same data, so moifying it will
# modify the original data
print(a[0,1])
b[0,0] = 77 
print(a[0,1])


[[2 3]
 [6 7]]
2
77


#### Mix integer indexing with slice indexing

In [17]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
